suite_name: "Product Analytics"
suite_description: "Tests for product-related analytics and metrics"
default_judge_criteria:
  accuracy_threshold: 8.0
  relevance_threshold: 9.0
  completeness_threshold: 8.0
  hallucination_threshold: 9.0
  require_exact_match: true

tests:
  - name: "product_total_quantities"
    question: "What is the total quantity ordered for each product?"
    sql: |
      SELECT
        p.product_id,
        p.name AS product_name,
        p.sku,
        SUM(od.quantity) AS total_quantity_ordered
      FROM products p
      JOIN order_details od ON p.product_id = od.product_id
      GROUP BY p.product_id, p.name, p.sku
      ORDER BY total_quantity_ordered DESC;
    tags: ["aggregation", "join", "ordering", "products"]

  - name: "highest_revenue_product"
    question: "Show me the product with the highest total revenue"
    sql: |
      SELECT
        p.product_id,
        p.name AS product_name,
        p.sku,
        SUM(od.quantity * od.final_unit_price) AS total_revenue
      FROM products p
      JOIN order_details od ON p.product_id = od.product_id
      GROUP BY p.product_id, p.name, p.sku
      ORDER BY total_revenue DESC
      LIMIT 1;
    tags: ["aggregation", "join", "calculation", "ordering", "limit", "products"]
